# Matrix product
Consider the following matrices A and B.

$$
A=
\begin{bmatrix} 
-1 & 2 & 3\\
4 & -5 & 6\\
7 & 8 & -9
\end{bmatrix}
$$

$$
B=
\begin{bmatrix} 
0 & 2 & 1\\
0 & 2 & -8\\
2 & 9 & -1
\end{bmatrix}
$$
When expressed in NumPy, it becomes as follows.


In [6]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("A=",a_ndarray,"\n\nB=",b_ndarray)

A= [[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]] 

B= [[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


## [Problem 1] Matrix product is calculated manually
Solve the matrix product of A and B by hand.

Please also explain the calculation process using markdown text.

Each element of the Product matrix AB can be calculated as follows:

$$
A=
\begin{bmatrix} 
a_11 & a_12 & a_13\\
a_21 & a_22 & a_23\\
a_31 & a_23 & a_33
\end{bmatrix}
$$

$$
B=
\begin{bmatrix} 
b_11 & b_12 & b_13\\
b_21 & b_22 & b_23\\
b_31 & b_23 & b_33
\end{bmatrix}
$$

$$
A*B=
\begin{bmatrix} 
 a_11*b_11 + a_12*b_21 + a_13*b_31 & a_11*a_12 + a_12*b_22 + a_13*b_23 & a_11*b_13 + a_12*b_23 + a_13*b_33\\
a_21*b_11 + a_22*b_21 + a_23*b_31 & a_21*a_12 + a_22*b_22 + a_23*b_23 & a_21*b_13 + a_22*b_23 + a_23*b_33\\
a_31*b_11 + a_23*b_21 + a_33*b_31 & a_31*a_12 + a_23*b_22 + a_33*b_23 & a_31*b_23 + a_23*b_23 + a_33*b_33
\end{bmatrix}
$$

$$
A*B=
\begin{bmatrix} 
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}
$$

## [Problem 2] Calculation by NumPy function

This matrix product of NumPy can be easily calculated using np.matmul() or np.dot() , or the @ operator.

Use these to calculate the matrix product.

In [4]:
import numpy as np
matrix_product_A_B=np.matmul(a_ndarray, b_ndarray)
print(matrix_product_A_B)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [5]:
print(a_ndarray@b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 3. Scratch implementation of matrix product
Without using np.matmul() , np.dot() , or @ operators, let's reproduce the calculation process performed by hand calculation from scratch implementation using NumPy. This will give you a better understanding of matrix product calculations. We limit ourselves to arrays of dimension 2 such as matrices A and B.

## [Problem 3] Implementation of calculation of a certain element
When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.

Expressed as a formula:
$$
% Summation in LaTeX
\[
\sum_{K=0}^{2}a0KbK0
\]
$$
Write code to do this calculation without using np.matmul() , np.dot() or @ operators.

In [13]:
print(a_ndarray[0][0]*b_ndarray[0][0]+a_ndarray[0][1]*b_ndarray[1][0]+a_ndarray[0][2]*b_ndarray[2][0])

6


## [Problem 4] Creating a function that performs matrix multiplication

Extend the code in Problem 3 to complete the matrix product scratch implementation. It should be a function that takes matrices A and B as arguments and returns the matrix product.

When calculating the matrix product, you will repeat the calculation in Problem 3 for different rows and columns.

It is the calculation result 3 × 3 
Each element of the matrix C of ci, j 
Is expressed as a formula as follows.

$$
% Summation in LaTeX
Cij=\[
\sum_{K=0}^{2}aiKbKj
\]
$$
By using the for statement and moving the index of ndarray, a total of 9 elements can be calculated. index  i Or j 
Increment by 1 to move to the next row or column.

In [83]:
def matrix_calculation(a=a_ndarray,b=b_ndarray):    
    result_array=np.zeros((a.shape[1],b.shape[1]))
    for i in range(a.shape[0]):
        counter=0
        for l in range (b.shape[1]):
            soma=0
            for j in range (a.shape[1]): 
                soma=soma+(a[i][j]*b[j][l])
            result_array[i][l]=soma
    print(result_array)
matrix_calculation()

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


Imagine DxE matrix product
The matrix product DE is defined when the number of columns of D is equal to the number of rows of E, so it cannot be calculated in this example.

## [Problem 5] Judge the input whose calculation is not defined
Depending on the implementation method, the function created in Problem 4 may work even if this D and E array is input. In this case, incorrect calculations will be made. Also, even if an error occurs in the middle, a message that is hard to understand why the error occurred is displayed directly.

You can prevent this by using an if statement or similar, and add code to display the problem in the input form using print() .

In [89]:
def matrix_calculation(a=np.array([[-1, 2, 3], [4, -5, 6]]),b=np.array([[-9, 8, 7], [6, -5, 4]])):    
    if(a.shape[1]==b.shape[0]):
        result_array=np.zeros((a.shape[1],b.shape[1]))
        for i in range(a.shape[0]):
            counter=0
            for l in range (b.shape[1]):
                soma=0
                for j in range (a.shape[1]): 
                    soma=soma+(a[i][j]*b[j][l])
                result_array[i][l]=soma
        return result_array
    else:
        return "If AxB are matrices and a calculation was supposed to be made an error has occured becaus the number of columns of A is equal to the number of rows of B"
print(matrix_calculation())

If AxB are matrices and a calculation was supposed to be made an error has occured becaus the number of columns of A is equal to the number of rows of B


## [Problem 6] Transposition
Transposing one matrix allows you to calculate the matrix product.

Transpose it using the np.transpose() or .T attributes and calculate the matrix product.

<mark>A missmatch error will occur!!!<mark> 

In [94]:
mat_a=np.array([[-1, 2, 3], [4, -5, 6]])
mat_b=np.array([[-9, 8, 7], [6, -5, 4]])
matrix_product_try=np.matmul(mat_a, mat_b)
print(matrix_product_try)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [96]:
new_mat_b=np.transpose(mat_b) #Transposing matrix
matrix_product_try=np.matmul(mat_a, new_mat_b)
print(matrix_product_try)

[[ 46  -4]
 [-34  73]]


And vice-versa... :)